### ISSUE TITLE
automatically add discovered functions

### ISSUE THREAD

**Issue by lockbox** [seeinglogic/ariadne#8]
the UX could be much smoother for embedded stuff if it autoanalyzed when a function lookup failed (or just in general if you find new code as you go along).

here: https://github.com/seeinglogic/ariadne/blob/dad7a16cfc11e9b2d6abab51edcc5d66b00f2b75/ariadne/target.py#L332

if the function lookup fails (ie. the `if self.function_dict.get(function, None) is None` then analyze the function and continue on

**Comment by seeinglogic** [comment]
It sounds like you're adding functions after Ariadne's analysis completes, but that not showing the new functions in the analysis is making the experience worse (because you don't want to redo analysis). Did I get that right?

Let me take a look at implementing auto-updating for new functions.

**Comment by lockbox** [comment]
Ah sorry edited the wording (analyze fails -> lookup fails) to make say what I mean.

Yes this is after doing the initial analysis, then define a new function in binary ninja and move focus into it - then ariadne explodes

**Comment by seeinglogic** [comment]
Thanks for bringing this to my attention, this is more involved than I thought it'd be.

Commit c7e9a8d catches the error, so you'll get a warning but nothing will break and you can continue to work as usual.

For now if you need to reflect the new functions, you can redo the analysis via the context menu `Ariadne -> Analyze Target` and the new functions will be reflected. Automatically adding functions as they're added is not as straightforward because Ariadne does target-wide analysis, so I'm looking at the best way to handle that.

I'll leave this open until I get auto-adding functions working.

**Comment by seeinglogic** [comment]
Sorry for taking so long on this, wanted to check and see if this was still pressing for anybody.

Since there's target-wide and cross-function stuff that needs to be updated, it requires careful management... in my attempts to solve this quickly, the async updates triggered some weird bugs and caused Binja to crash.

The simplest way to manage this is to force a global update as described in the previous comment; please let me know if this is dealbreaker for you.

**Comment by lockbox** [comment]
forcing a global update works for me, thats a decent enough workaround and is basically the workflow i was using anyways, though sometimes i turn it off for a sec when adding a bunch of functions on a very large binary then toggle it back on and let it rip
